version: "3.8"

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: uid:gid
    network_mode: 'host'
    volumes:
      # - /path/to/config:/config
      # - /path/to/cache:/cache
      # - /path/to/media:/media
      # - /path/to/media2:/media2:ro
      - ./jellyfin/data:/data
      - /media/samba/mount:/media
    restart: 'unless-stopped'
    env_file:
      - .env
    environment:
      - JELLYFIN_PublishedServerUrl=http://localhost
      - JELLYFIN_DATA_DIR:/data
      
    # Optional - alternative address used for autodiscovery
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - "host.docker.internal:host-gateway"
