version: "3.8"

services:
  foundry:
    image: felddy/foundryvtt:release
    hostname: localhost
    init: true
    volumes:
      - type: bind
        source: ./foundryvtt/data
        target: /data
    env_file:
      - ./foundryvtt/.env
    environment:
      - CONTAINER_CACHE=./data/container_cache
      - FOUNDRY_MINIFY_STATIC_FILES=true
      - TIMEZONE=EDT
    ports:
      - target: 30000
        published: 30000
        protocol: tcp
